
title: 1984.solutions
email: hi@1984.solutions
description:
urlbase: ""
url: "https://1984.solutions"
markdown: kramdown

permalink: /blog/:title/

exclude:
  - .git
  - .gitignore
  - .DS_Store
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - build.sh
  - run.sh
  - stop.sh
  - Dockerfile
  - docker-compose.yaml

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
